# -*- coding: utf-8 -*-
"""Untitled7.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/10a2W8ZFC9Bb_9Cl3F9YAp6coGE96Rx56
"""

gejala_user = {
    "nyeri_dada": 0.4,
    "bengkak_sendi": 0.3,
    "kaku_sendi_pagi": 0.5,
    "demam_ringan": 0.1,
    "sesak_napas": 0.6,
    "nyeri_sendi2": 0.4,
    "kram_otot": 0.5,
    "lemas": 0.7,
    "pegal": 0.3
}

pengetahuan = {
    "rheumatoid_arthritis": {
        "nyeri_dada": 0.9,
        "bengkak_sendi": 0.8,
        "kaku_sendi_pagi": 0.9,
        "demam_ringan": 0.4,
        "sesak_napas": 0.7,
        "nyeri_sendi2": 0.5,
        "kram_otot": 0.6,
        "lemas": 0.6,
        "pegal": 0.4
    },
    "osteoarthritis": {
        "nyeri_dada": 0.8,
        "bengkak_sendi": 0.6,
        "kaku_sendi_pagi": 0.5,
        "sesak_napas": 0.4,
        "kram_otot": 0.3,
        "lemas": 0.7
    }
}

def hitung_cf(gejala_user, pengetahuan_pakar):
    cf_total = 0
    first = True
    for gejala, cf_user in gejala_user.items():
        if gejala in pengetahuan_pakar:
            cf_pakar = pengetahuan_pakar[gejala]
            cf = cf_user * cf_pakar
            if first:
                cf_total = cf
                first = False
            else:
                cf_total = cf_total + cf * (1 - cf_total)
    return cf_total

# Mendiagnosa dua penyakit berdasarkan gejala yang sama
for penyakit in pengetahuan:
    cf_result = hitung_cf(gejala_user, pengetahuan[penyakit])
    print(f"CF diagnosis {penyakit}: {cf_result:.2f}")

    """"1.Ubah nilai CF gejala dan amati perubahan hasil
jawab:Saya mengganti nilai gejala menjadi: demam 0.3, batuk 0.2, dan sakit tenggorokan 0.1. Hasil yang diperoleh adalah CF sebesar 0.39. Namun ketika nilai-nilai tersebut dinaikkan menjadi demam 1.0, batuk 1.0, dan sakit tenggorokan 1.0, maka CF diagnosis flu meningkat signifikan hingga mencapai 0.98.


---


2.Tambahkan 5 gejala baru seperti dengan nilai CF.
jawab:Saya menambahkan lima gejala tambahan, yaitu: sakit gigi (0.8), sakit kepala (0.6), flu (0.5), asma (0.4), dan sesak napas (0.7).


---

3.Jika "demam" diubah jadi 0.2, bagaimana hasilnya? Mengapa?
jawab:Saat nilai CF untuk gejala demam diturunkan menjadi 0.2, nilai akhir CF juga menjadi lebih rendah. Hal ini disebabkan karena demam merupakan gejala pertama yang dihitung, sehingga memiliki pengaruh besar terhadap proses penggabungan nilai-nilai CF dari gejala berikutnya. Dengan nilai awal yang rendah, kontribusi dari gejala lain menjadi tidak maksimal. Sebagai ilustrasi, sebelumnya dengan nilai demam 0.56, hasil akhir CF bisa mencapai 0.97. Setelah diturunkan ke 0.2, hasil akhirnya turun menjadi sekitar 0.85.
"""

gejala_user = {
    "nyeri_dada": 0.4,
    "bengkak_sendi": 0.3,
    "kaku_sendi_pagi": 0.5,
    "demam_ringan": 0.1,
    "sesak_napas": 0.6,
    "nyeri_sendi2": 0.4,
    "kram_otot": 0.5,
    "lemas": 0.7,
    "pegal": 0.3
}

pengetahuan = {
    "rheumatoid_arthritis": {
        "nyeri_dada": 0.9,
        "bengkak_sendi": 0.8,
        "kaku_sendi_pagi": 0.9,
        "demam_ringan": 0.4,
        "sesak_napas": 0.7,
        "nyeri_sendi2": 0.5,
        "kram_otot": 0.6,
        "lemas": 0.6,
        "pegal": 0.4
    },
    "osteoarthritis": {
        "nyeri_dada": 0.8,
        "bengkak_sendi": 0.6,
        "kaku_sendi_pagi": 0.5,
        "sesak_napas": 0.4,
        "kram_otot": 0.3,
        "lemas": 0.7
    }
}

def hitung_cf(gejala_user, pengetahuan_pakar):
    cf_total = 0
    first = True
    for gejala, cf_user in gejala_user.items():
        if gejala in pengetahuan_pakar:
            cf_pakar = pengetahuan_pakar[gejala]
            cf = cf_user * cf_pakar
            if first:
                cf_total = cf
                first = False
            else:
                cf_total = cf_total + cf * (1 - cf_total)
    return cf_total

# Mendiagnosa dua penyakit berdasarkan gejala yang sama
for penyakit in pengetahuan:
    cf_result = hitung_cf(gejala_user, pengetahuan[penyakit])
    print(f"CF diagnosis {penyakit}: {cf_result:.2f}")

"""""1 CF : Ubah nilai CF gejala dan amati perubahan hasil,
Jawab : Saya mengubah nilai gejala nyeri_dada : 0.4, bengkak_sendi : 0.3, kaku_sendi_pagi : 0.5, demam_ringan : 0.1, yang terjadi adalah pada Rheumatoid Arthritis CFnya yang sebelumnya 0.98, sekarang menjadi 0.74, Osteoarthritis yang sebelumnya 0.89 sekarang menjadi 0.58, kenapa bisa seperti itu? karena nilai CF yang sudah diinputkan tingkat keyakinan usernya terhadap gejala lebih rendah.


---
2.Soal 2 CF : Tambahkan 5 gejala baru seperti dengan nilai CF,
jawab : Saya menambahkan lima gejala baru, yaitu sesak_napas: (0.7),nyeri_sendi: (0.5), kram_otot: (0.6), lemas: (0.6), pegal: (0.4)

"""

gejala_user = {
    "sering_haus": 0.9,
    "sering_buang_air_kecil": 0.6,
    "penurunan_berat_badan": 0.8,
    "luka_lambat_sembuh": 0.5,
    "penglihatan_kabur": 0.5,
    "kelelahan": 0.7,
    "kesemutan": 0.5,
    "mual": 0.4,
    "pusing": 0.6,
    "batuk": 0.3
}

pengetahuan = {
    "diabetes_tipe_1": {
        "sering_haus": 0.9,
        "sering_buang_air_kecil": 0.8,
        "penurunan_berat_badan": 0.7,
        "luka_lambat_sembuh": 0.5,
        "kelelahan": 0.8,
        "kesemutan": 0.6,
        "mual": 0.5,
        "pusing": 0.6,
        "batuk": 0.4
    },
    "diabetes_tipe_2": {
        "sering_haus": 0.7,
        "sering_buang_air_kecil": 0.7,
        "penurunan_berat_badan": 0.5,
        "luka_lambat_sembuh": 0.8,
        "penglihatan_kabur": 0.6,
        "kelelahan": 0.7,
        "kesemutan": 0.5,
        "mual": 0.4,
        "pusing": 0.5,
        "batuk": 0.3
    }
}

# Bobot kepentingan gejala (1-5)
bobot_gejala = {
    "sering_haus": 4,
    "sering_buang_air_kecil": 4,
    "penurunan_berat_badan": 3,
    "luka_lambat_sembuh": 5,
    "penglihatan_kabur": 2,
    "kelelahan": 4,
    "kesemutan": 3,
    "mual": 2,
    "pusing": 3,
    "batuk": 1
}

def hitung_cf_weighted(gejala_user, pengetahuan_pakar, bobot):
  cf_total = 0
  first = True
  total_bobot = 0

  for gejala, cf_user in gejala_user.items():
    if gejala in pengetahuan_pakar and gejala in bobot:
      cf_pakar = pengetahuan_pakar[gejala]
      gejala_weight = bobot[gejala] / 5 #Normalisasi bobot (1-5) -> (0.2-1.8)
      cf = cf_user * cf_pakar * gejala_weight

      if first:
        cf_total = cf
        first = False
      else:
        cf_total = cf_total + cf * (1 - cf_total)

      total_bobot += gejala_weight
  # Normalisasi hasil berdasarkan total bobot
  if total_bobot > 0:
    cf_total / total_bobot * len([g for g in gejala_user if g in pengetahuan_pakar])

  return cf_total

for penyakit in pengetahuan:
  cf_result = hitung_cf_weighted(gejala_user, pengetahuan[penyakit], bobot_gejala)
  print(f"CF diagnosis {penyakit}: {cf_result:.2f}")

""""1 CF : Ubah nilai CF gejala dan amati perubahan hasil,
Jawab : Saya mengubah nilai CF gejala sering_haus : 0.9, sering_buang_air_kecil : 0.6, penurunan_berat_badan : 0.8, luka_lambat_sembuh : 0.5, penglihatan_kabur : 0.5, hasilnya diabetes tipe 1 sebelumnya 0.91, diabetes tipe 2 0.91, maka nilai diabetes tipe 1 sekarang : 0.89, dan diabetes tipe 2 sekarang : 0.87, kenapa bisa seperti itu? karena pada diabetes tipe 1 penurunan pada luka_lambat_sembuh dan kenaikan pada sering_haus dan penurunan_berat_badan sedikit mengubah hasil, cuman tetap diagnosisnya menjadi cukup tinggi 0.89, sedangkan diabetes tipe 2, hasil diagnosis tersebut tetap stabil meskipun ada perubahan pada beberapa gejala, nilai CFnya juga tetap tinggi menjadi 0.87, ini menunjukan penurunan atau kenaikan gejala memiliki dampak signifikan pada hasil akhir.


---

2.Tambahkan 5 gejala baru seperti dengan nilai CF.
jawab: Saya telah menambahkan lima gejala baru pada data gejala pengguna, yaitu: kelelahan dengan nilai CF 0.7, kesemutan 0.5, mual 0.4, pusing 0.6, dan infeksi 0.3. Selain itu, gejala-gejala ini juga ditambahkan ke basis pengetahuan dengan nilai CF sebagai berikut: kelelahan 0.9, kesemutan 0.6, mual 0.5, pusing 0.6, dan infeksi 0.4. Untuk kategori diabetes tipe 2, gejala-gejala tersebut juga dimasukkan dengan nilai CF: kelelahan 0.7, kesemutan 0.5, mual 0.4, pusing 0.5, dan infeksi 0.3. Di sisi lain, bobot gejala ditambahkan masing-masing: kelelahan 4, kesemutan 3, mual 2, pusing 3, dan infeksi 1.

Setelah penambahan ini, hasil diagnosis untuk diabetes tipe 1 meningkat secara signifikan menjadi 0.97, sedangkan untuk diabetes tipe 2 naik menjadi 0.94. Kenaikan pada diabetes tipe 1 disebabkan oleh gejala seperti kelelahan dan kesemutan yang memberikan dampak positif yang kuat. Sementara itu, untuk diabetes tipe 2, meskipun nilai beberapa gejala lebih rendah, gejala seperti kelelahan dan pusing tetap berkontribusi besar terhadap hasil diagnosis. Kesimpulannya, penambahan gejala-gejala baru ini secara umum meningkatkan akurasi dalam mendiagnosis kedua jenis diabetes.
"""